spring:
  application:
    name: driver-services
  datasource:
    url: jdbc:oracle:thin:@10.90.1.105:1521/DEV
    username: HR
    password: HR
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true  
    properties:
      hibernate:
        format_sql: true
     
server:
  port: 2020
  
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8762/eureka
      
management:
  endpoints:
    web:
      exposure:
        include:
        - "*"  